### ISSUE TITLE
Image not load into epubview

### ISSUE THREAD

**Issue by developerdesigner18** [HamedTaherpour/ht-epub-reader-android#1]
When i download the file and try to load into epub then  only text and link is loaded image was not can you please help me to solve this issue.

**Comment by developerdesigner18** [comment]
> When i download the file and try to load into epub then only text and link is loaded image was not can you please help me to solve this issue.

on this issue you can modify 1 file and using it.(add **getSettings().setAllowFileAccess(true);** in **generateHtmlContent** method in **EpubView.java file)**

**Comment by HamedTaherpour** [comment]
> 
> 
> When i download the file and try to load into epub then only text and link is loaded image was not can you please help me to solve this issue.

if you set the `targetSdkVersion` under 30 everything  going to fine

**Comment by HamedTaherpour** [comment]
> 
> 
> > When i download the file and try to load into epub then only text and link is loaded image was not can you please help me to solve this issue.
> 
> on this issue you can modify 1 file and using it.(add **getSettings().setAllowFileAccess(true);** in **generateHtmlContent** method in **EpubView.java file)**

Thanks, the problem is solved, now you can
