### ISSUE TITLE
Problem with some epub files

### ISSUE THREAD

**Issue by jayantur13** [HamedTaherpour/ht-epub-reader-android#2]
The file gets downloaded,but when I open it,it just shows Error (that means no sublist too), the sample you provided works properly..When the link is not a valid epub,app gets crash.

@HamedTaherpour

**Comment by HamedTaherpour** [comment]
Hi
please send me your ePub file, may be needed for up to date the plugin.

Thank you

**Comment by jayantur13** [comment]
Thank you for reply..I tried epub from different websites.

Epub from Smashwords - https://www.smashwords.com/books/view/1055191 , Epub (with images) from Project Gutenberg - https://www.gutenberg.org/ebooks/63816 ,Epub Open library - https://openlibrary.org/books/OL23356819M/Virgin_soil, Epub Digi Libraries - https://digilibraries.com/ebook/little-women

I think more epub's must be tested, because it contains different structure in different websites..Github not allows epub attachment,so I provided links..Hope, this will help the library.

Edit - Some book can have two authors.

Regards..

**Comment by HamedTaherpour** [comment]
Yes, it does take time to solve the problem
I try to solve problems at the first opportunity

**Comment by HamedTaherpour** [comment]
Hi
Thanks for reporting the problem
The problem is solved
Check out

**Comment by jayantur13** [comment]
Still,I am not able to load epubs.Am I doing something wrong ?

**Comment by jayantur13** [comment]
Still,I am not able to load few epubs https://www.smashwords.com/books/view/1055191,https://hamedtaherpour.github.io/sample-assets/epub/book-2.epub.Am I doing something wrong ? For showing sublist I'm using Dialog,sometimes book cover not show and sometimes both author and title not load,sometimes the sublist doesn't appear. (Maybe they are null or empty).Refracted a small code change too.

But I appreciate your efforts,most of epub are working only a few ones not.

Thank you so much.

**Comment by HamedTaherpour** [comment]
I solved all problems , i think you must check all of your ePub file before your use this library, or check it with use the log to know every thing is fine.

**Comment by jayantur13** [comment]
I don't know what is wrong on my side..I am trying my best to figure out the problem.As you said there's no problem now,I should mark this as solved then.

Edit - I got the problem and solved it.

Thank you.
