### ISSUE TITLE
[Question] On-demand extraction?

### ISSUE THREAD

**Issue by HubKing** [HamedTaherpour/ht-epub-reader-android#3]
If I understood it correctly, it seems that this library extracts all resource files in an ePub file to the storage. Is this necessary? Isn't it more efficient to extract only the requested (by the user of the library) resources into memory on-demand, without using the storage?

**Comment by HamedTaherpour** [comment]
Yes, but we need this for developing fastness and having control on file in ePub
Do you want to add this option that user of the library remove the file if needed?

**Comment by HubKing** [comment]
On second thought, it seems that most ePub viewers are using a web browser control anyway, and the browser probably needs all linked files readily accessible, so maybe decompressing all files is easier and efficient way overall. But how about caching those extracted files and do not extracting them again when opening the same ePub next time? I may be wrong, but judging by the code, it seems that this library extracts all files every time, and probably overwriting existing extracted files from previous opening. You could add a simple method like `deleteCache(ePub file name)` that deletes all the extracted files for that ePub.
